###
# This script generates the graphs included in the thesis. Only the time domain 
# graphs are not generated by this script.
# The data files "trials.csv", "no_hands.csv", "avg_blocks.csv" and 
# "dev_blocks.csv" are required.
# They should be placed in the "data\" folder.
###
# The script saves the figures to "figures/" folder.
###
# Written by S. Drauksas, 2022
###
library(tidyverse)
library(janitor)
library(ggpubr)

# Performance Improvement ----
trials <- read_csv("data/trials.csv")
trials$ID <- as.factor(trials$ID)
trials$Group <- as.factor(trials$Group)
trials$Trial <- factor(trials$Trial, levels=c("BL", "T1", "MTR", "T2", "ETR"))

t1_imp <- trials[trials$Trial == "T1",]
t2_imp <- trials[trials$Trial == "T2",]

t1_imp$Score <- trials[trials$Trial == "T1",]$Score - trials[trials$Trial == "BL",]$Score
t1_imp$Variance <- trials[trials$Trial == "T1",]$Variance - trials[trials$Trial == "BL",]$Variance

t2_imp$Score <- trials[trials$Trial == "T2",]$Score - trials[trials$Trial == "MTR",]$Score
t2_imp$Variance <- trials[trials$Trial == "T2",]$Variance - trials[trials$Trial == "MTR",]$Variance

t_imp <- rbind(t1_imp, t2_imp)

t_imp_sc <- ggboxplot(t_imp,
                      x = "Trial",
                      y = "Score",
                      fill = "Group",
                      alpha = 1,
                      xlab = "Trial",
                      ylab = "Difference",
                      legend.title = "Group",
                      add = "dotplot",
                      palette = c("#00A6D6", "#E03C31"),
                      ylim = c(-10, 10)) + grids(axis = "y")

t_imp_var <- ggboxplot(t_imp,
                       x = "Trial",
                       y = "Variance",
                       fill = "Group",
                       alpha = 1,
                       xlab = "Trial",
                       ylab = "Difference",
                       legend.title = "Group",
                       add = "dotplot",
                       palette = c("#00A6D6", "#E03C31"),
                       ylim = c(-10, 10)) + grids(axis = "y")

ggsave(filename = "TImpSc.png",
       path = "figures",
       plot = t_imp_sc,
       device = "png",
       dpi = "retina",
       width = 170,
       height = 126,
       units = "mm")
ggsave(filename = "TImpVar.png",
       path = "figures",
       plot = t_imp_var,
       device = "png",
       dpi = "retina",
       width = 170,
       height = 126,
       units = "mm")

# No Hands Score Distribution ----
nh <- read_csv("data/no_hands.csv")
#nh$scenario <- factor(nh$scenario, levels = nh$scenario)

nh_plot <- ggboxplot(data = nh,
                     x = "scenario",
                     y = "score",
                     fill = "scenario",
                     xlab = "Scenario",
                     ylab = "Score",
                     palette = c("#00A6D6", "#E03C31", "#6CC24A"),
                     legend = "none",
                     add = "jitter") +
  grids(axis = "y") +
  scale_x_discrete(breaks = c("NH_NC", "NH_C", "ETR"))

ggsave(filename = "NH.png",
       path = "figures",
       plot = nh_plot,
       device = "png",
       dpi = "retina",
       width = 178,
       height = 63,
       units = "mm")

# Skill Dependency ----
imp <- c(trials[trials$Group == 1 & trials$Trial == "MTR",]$Score - trials[trials$Group == 1 & trials$Trial == "BL",]$Score,
             trials[trials$Group == 2 & trials$Trial == "ETR",]$Score - trials[trials$Group == 2 & trials$Trial == "MTR",]$Score)
init <- c(trials[trials$Group == 1 & trials$Trial == "BL",]$Score,
              trials[trials$Group == 2 & trials$Trial == "MTR",]$Score)
id <- c(trials[trials$Group == 1 & trials$Trial == "MTR",]$ID,
            trials[trials$Group == 2 & trials$Trial == "ETR",]$ID)
ctrl <- rep("On", 10)
cOn <- data.frame(imp, init, id, ctrl)

imp <- c(trials[trials$Group == 1 & trials$Trial == "ETR",]$Score - trials[trials$Group == 1 & trials$Trial == "MTR",]$Score,
              trials[trials$Group == 2 & trials$Trial == "MTR",]$Score - trials[trials$Group == 2 & trials$Trial == "BL",]$Score)
init <- c(trials[trials$Group == 1 & trials$Trial == "MTR",]$Score,
               trials[trials$Group == 2 & trials$Trial == "BL",]$Score)
id <- c(trials[trials$Group == 1 & trials$Trial == "ETR",]$ID,
            trials[trials$Group == 2 & trials$Trial == "MTR",]$ID)
ctrl <- rep("Off", 10)
cOff <- data.frame(imp, init, id, ctrl)

skill <- rbind(cOn, cOff)
skill$ctrl <- as.factor(skill$ctrl)

skill_scatter <- ggscatter(data = skill,
                           x = "init",
                           y = "imp",
                           color = "ctrl",
                           xlab = "Initial Skill",
                           ylab = "Difference",
                           legend.title = "Controller State",
                           add = "reg.line",
                           palette = c("#00A6D6", "#E03C31")) +
  stat_cor(aes(color = ctrl), label.x = 90) +
  geom_vline(xintercept = 87, color = "#6CC24A") +
  grids(axis = "y")

skill$grp <- "High"
skill[skill$init < 87,]$grp <- "Low"

skill_box <- ggboxplot(data = skill,
                       x = "grp",
                       y = "imp",
                       fill = "ctrl",
                       xlab = "Skill Group",
                       ylab = "Difference",
                       legend.title = "Controller State",
                       palette = c("#00A6D6", "#E03C31"),
                       ylim = c(-5, 15)) +
  grids(axis = "y") +
  geom_bracket(xmin = 1,
               xmax = 2,
               label = "p = 0.002",
               y.position = 12)

ggsave(filename = "SkillScatt.png",
       path = "figures",
       plot = skill_scatter,
       device = "png",
       dpi = "retina",
       width = 85*2,
       height = 63*2,
       units = "mm")

ggsave(filename = "SkillBox.png",
       path = "figures",
       plot = skill_box,
       device = "png",
       dpi = "retina",
       width = 85*2,
       height = 63*2,
       units = "mm")

# Score Evolution ----
delft_palette = c("#0C2340", "#A50034", "#EC6842", "#00B8C8", "#0076C2",
                  "#6F1D77", "#EF60A3", "#E03C31", "#FFB81C", "#6CC24A")
block_sc <- read_csv("data/avg_blocks.csv")
block_sc <- gather(data = block_sc,
                   key = "Trial",
                   value = "Sc",
                   BL.1, BL.2, 
                   T1.1, T1.2, T1.3, T1.4, T1.5, T1.6,
                   MTR.1, MTR.2,
                   T2.1, T2.2, T2.3, T2.4, T2.5, T2.6,
                   ETR.1, ETR.2,
                   factor_key = TRUE)
block_sc$ID <- as.factor(block_sc$ID)
block_sc$Grp <- as.factor(block_sc$Grp)

block_var <- read_csv("data/dev_blocks.csv")
block_var <- gather(data = block_var,
                    key = "Trial",
                    value = "Var",
                    BL.1, BL.2, 
                    T1.1, T1.2, T1.3, T1.4, T1.5, T1.6,
                    MTR.1, MTR.2,
                    T2.1, T2.2, T2.3, T2.4, T2.5, T2.6,
                    ETR.1, ETR.2,
                    factor_key = TRUE)
block_var$ID <- as.factor(block_var$ID)
block_var$Grp <- as.factor(block_var$Grp)

evol_sc_grp <- ggline(data = block_sc,
                      x = "Trial",
                      y = "Sc",
                      color = "ID",
                      palette = delft_palette,
                      xlab = "Block",
                      ylab = "Score",
                      legend = "Participant",
                      ylim = c(65, 100),
                      facet.by = "Grp",
                      panel.labs = list(Grp = c("Group 1", "Group 2"))) + 
  rotate_x_text(45) +
  grids(axis = "xy")

evol_var_grp <- ggline(data = block_var,
                       x = "Trial",
                       y = "Var",
                       color = "ID",
                       palette = delft_palette,
                       xlab = "Block",
                       ylab = "Variance",
                       legend = "Participant",
                       ylim = c(0, 40),
                       facet.by = "Grp",
                       panel.labs = list(Grp = c("Group 1", "Group 2"))) + 
  rotate_x_text(45) +
  grids(axis = "xy")

ggsave("ScoreEvolGrp.png",
       path = "figures",
       plot = evol_sc_grp,
       device = "png",
       width = 237,
       height = 157,
       units = "mm",
       dpi = "retina")

ggsave("VarEvolGrp.png",
       path = "figures",
       plot = evol_var_grp,
       device = "png",
       width = 237,
       height = 157,
       units = "mm",
       dpi = "retina")

# Score Barplot ----
score_bar <- ggbarplot(data = trials,
                x = "Trial",
                y = "Score",
                facet.by = "Group",
                fill = "Group",
                add = c("mean_sd"),
                palette = c("#00A6D6", "#E03C31"),
                panel.labs = list(Group = c("Group 1", "Group2"))) +
  grids(axis = "y") +
  rremove("legend")

variance_bar <- ggbarplot(data = trials,
                          x = "Trial",
                          y = "Variance",
                          facet.by = "Group",
                          fill = "Group",
                          add = c("mean_sd"),
                          palette = c("#00A6D6", "#E03C31"),
                          panel.labs = list(Group = c("Group 1", "Group2"))) +
  grids(axis = "y") +
  rremove("legend")

ggsave("ScoreBar.png",
       path = "figures",
       plot = score_bar,
       device = "png",
       width = 237,
       height = 157,
       units = "mm",
       dpi = "retina")

ggsave("VarBar.png",
       path = "figures",
       plot = variance_bar,
       device = "png",
       width = 237,
       height = 157,
       units = "mm",
       dpi = "retina")

# PRESENTATION FIGURES ----
# Slightly adjusted graphs for the presentation. Overwrites the originals!
# t_imp_sc <- ggboxplot(t_imp,
#                       x = "Trial",
#                       y = "Score",
#                       fill = "Group",
#                       alpha = 1,
#                       xlab = "Trial",
#                       ylab = "Difference in mean scores.\nHigher is better.",
#                       legend.title = "Group",
#                       add = "dotplot",
#                       palette = c("#00A6D6", "#E03C31"),
#                       ylim = c(-10, 10)) + grids(axis = "y") +
#   scale_x_discrete(labels = c("T1 - BL", "T2 - MTR"))
# 
# t_imp_var <- ggboxplot(t_imp,
#                        x = "Trial",
#                        y = "Variance",
#                        fill = "Group",
#                        alpha = 1,
#                        xlab = "Trial",
#                        ylab = "Difference in score variance.\nLower is better.",
#                        legend.title = "Group",
#                        add = "dotplot",
#                        palette = c("#00A6D6", "#E03C31"),
#                        ylim = c(-10, 10)) + grids(axis = "y") +
#   scale_x_discrete(labels = c("T1 - BL", "T2 - MTR"))
# 
# ggsave(filename = "TImpSc.png",
#        path = "figures",
#        plot = t_imp_sc,
#        device = "png",
#        dpi = "retina",
#        width = 470*2,
#        height = 640*2,
#        units = "px")
# ggsave(filename = "TImpVar.png",
#        path = "figures",
#        plot = t_imp_var,
#        device = "png",
#        dpi = "retina",
#        width = 470*2,
#        height = 640*2,
#        units = "px")

# skill_scatter <- ggscatter(data = skill,
#                            x = "init",
#                            y = "imp",
#                            color = "ctrl",
#                            xlab = "Initial Skill",
#                            ylab = "Mean score improvement",
#                            legend.title = "Controller State",
#                            add = "reg.line",
#                            palette = c("#00A6D6", "#E03C31")) +
#   stat_cor(aes(color = ctrl), label.x = 90) +
#   #geom_vline(xintercept = 87, color = "#6CC24A") +
#   grids(axis = "y")
# 
# ggsave(filename = "SkillScatt.png",
#        path = "figures",
#        plot = skill_scatter,
#        device = "png",
#        dpi = "retina",
#        width = 460*2*2,
#        height = 600*2,
#        units = "px")

# nh <- nh[nh$scenario == "NH_NC" | nh$scenario == "NH_C",]
# #nh$scenario <- factor(nh$scenario, levels = nh$scenario)
# 
# nh_plot <- ggboxplot(data = nh,
#                      x = "scenario",
#                      y = "score",
#                      fill = "scenario",
#                      xlab = "Scenario",
#                      ylab = "Score",
#                      palette = c("#00A6D6", "#E03C31", "#6CC24A"),
#                      legend = "none",
#                      add = "jitter") +
#   grids(axis = "y") +
#   scale_x_discrete(breaks = c("NH_NC", "NH_C"), labels = c("No Controller", "Controller"))
# 
# ggsave(filename = "NH.png",
#        path = "figures",
#        plot = nh_plot,
#        device = "png",
#        dpi = "retina",
#        width = 460*2*2,
#        height = 650,
#        units = "px")