function csvSimData(foldername, filename)
% Extracts the data from a .mat file, and writes it into a .csv file.
% Works only for simulation data, as the trial begins right away (at t = 0s).
%
% INPUTS:
%   fileName - string with a filename and extension of the file of interest
%
% Written by S. Drauksas, 2022

%% Load the file and extract the data
load(fileName);
% Extract bicycle state data
bikeState = timeseries2timetable(out.BicycleState);
bikeState = timetable(bikeState.Time, ...
                      bikeState.Data(:,1), ...
                      bikeState.Data(:,2), ...
                      bikeState.Data(:,3), ...
                      bikeState.Data(:,4), ...
                      bikeState.Data(:,5), ...
                      bikeState.Data(:,6), ...
                      VariableNames={'y_P', ...
                                     'psi', ...
                                     'phi', ...
                                     'delta', ...
                                     'd_phi', ...
                                     'd_delta'});
% Extract MPC data
mpcStats = timeseries2timetable(out.MpcStats.fval, ...
                                out.MpcStats.flag, ...
                                out.MpcStats.iter);
mpcTorque = timeseries2timetable(out.SteerTorque);
% Extract reference data, keep only the current timestep values, discard future
reference = timeseries2timetable(out.Reference);
reference = timetable(reference.Time,...
                      reference.Data(:,1), ...
                      reference.Data(:,2), ...
                      reference.Data(:,3), ...
                      reference.Data(:,4), ...
                      reference.Data(:,5), ...
                      reference.Data(:,6), ...
                      VariableNames={'ref_y_P', ...
                                     'ref_psi', ...
                                     'ref_phi', ...
                                     'ref_delta', ...
                                     'ref_d_phi', ...
                                     'ref_d_delta'});
% Put all data into one timetable
synch = synchronize(bikeState, ...
                    mpcStats, ...
                    mpcTorque, ...
                    reference, ...
                    'union','previous');

%% Find the time range of the trial
len = 480; % Simulation has two trials - 2min no controller + 6min controller

t = timerange(seconds(0), ...
              seconds(len));

%% Write the table
rawTable = timetable2table(synch(t,:));
writetable(rawTable, fileName + "_Data.csv");
end